### ISSUE TITLE
Apartado 9 Varnish Cache

### ISSUE THREAD

**Issue by JuanJoseMoralesC** [MUIT-RdDC-UAH-University/vagrant-bind9-varnish-RdDC#1]
Buenas, tal y como establece el apartado 9 a la hora de pinchar sobre los enlaces "Blue" y "Red", al no funcionar el navegador como podemos realizarlo. 

Gracias de antemano.

**Comment by JuanJoseMoralesC** [comment]
Lo hemos solucionado realizando curl varnish.example.com/red/index.html

**Comment by JuanJoseMoralesC** [comment]
Aunque no tenemos claro que este bien.

**Comment by imyelmo** [comment]
¿Qué url consultabais antes? También depende de la IP que el DNS resuelva de varnish.example.com

**Comment by diegoLopezP** [comment]
Para comprobar si los contenidos son cacheables (o no), podes utilizar el navegador Firefox incluido en S.O de Ubuntu. Lo único, que no podréis acceder a la dirección web varnish.example.com desde dicho navegador (no la va a resolver la dirección el servidor DNS porque no habéis configurado el S.O para que "apunte" a vuestro DNS), tendréis que hacerlo poniendo directamente la dirección IP de los servidores varnish. 

En cuanto al balanceo por DNS, sí podéis utilizar curl desde el contenedor cliente, porque ahí se ve como hace el balanceo el DNS tras sucesivas peticiones (se ve el código html de la página web consultada, en el que pone si corresponde al servidor 1 o 2).

Por cierto, las siguientes dudas las ponéis dentro del repositorio _RdDC-2022-23-General_, para agrupar todas las dudas en un único punto y que sean accesibles por todos los compañeros.

**Comment by JuanJoseMoralesC** [comment]
Al final conseguimos solucionarlo, gracias a ambos.
