### ISSUE TITLE
Blue y red cacheables

### ISSUE THREAD

**Issue by Ruben-Com** [MUIT-RdDC-UAH-University/vagrant-bind9-varnish-RdDC#2]
Al hacer curl a las páginas red y blue se cachean ambas páginas. Sospechamos que pueda ser similar a este problema publicado en Stackoverflow:
https://stackoverflow.com/questions/17824848/is-meta-http-equiv-value-cache-control-is-not-supported

**Comment by Ruben-Com** [comment]
Creemos que al realizar el curl a las páginas red y blue no considera la etiqueta <meta http-equiv> y que, si se hicieran a través de algún navegador como Firefox a través de Remmina, se tendría en cuenta la etiqueta y podría funcionar correctamente.

**Comment by imyelmo** [comment]
Hola, ¿las etiquetas son iguales para esperar el mismo comportamiento? En cualquier caso, la manera de estar seguro de ello es usar un navegador ya sea tradicional (firefox) o en modo consola (lynx).

**Comment by diegoLopezP** [comment]
Para comprobar si los contenidos son cacheables (o no), tenéis que utilizar el navegador Firefox incluido en S.O de Ubuntu. Lo único, que no podréis acceder a la dirección web varnish.example.com desde dicho navegador (no la va a resolver la dirección el servidor DNS porque no habéis configurado el S.O para que "apunte" a vuestro DNS), tendréis que hacerlo poniendo directamente la dirección IP de los servidores varnish. Curl al no soportar el tag meta, "lo omite" y por tanto no veréis el comportamiento esperado.

Por cierto, las siguientes dudas las ponéis dentro del repositorio _RdDC-2022-23-General_, dentro del apartado Issues, para agrupar todas las dudas en un único punto y que sean accesibles por todos los compañeros.
